// This file is auto-generated by @hey-api/openapi-ts

export { Admin, type Options, Referral } from './sdk.gen';
export type { ClientOptions, CreateReferralRequest, CreateReferralResponse, GetApiReferralByReferralCodeData, GetApiReferralByReferralCodeResponse, GetApiReferralByReferralCodeResponses, MarkRedeemedRequest, MarkRedeemedResponse, PostApiAdminRedeemData, PostApiAdminRedeemResponse, PostApiAdminRedeemResponses, PostApiReferralData, PostApiReferralResponse, PostApiReferralResponses, ReferralDetailsResponse } from './types.gen';
