// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiReferralByReferralCodeData, GetApiReferralByReferralCodeResponses, PostApiAdminRedeemData, PostApiAdminRedeemResponses, PostApiReferralData, PostApiReferralResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Admin {
    public static postApiAdminRedeem<ThrowOnError extends boolean = false>(options?: Options<PostApiAdminRedeemData, ThrowOnError>) {
        return (options?.client ?? client).post<PostApiAdminRedeemResponses, unknown, ThrowOnError>({
            url: '/api/Admin/redeem',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class Referral {
    public static postApiReferral<ThrowOnError extends boolean = false>(options?: Options<PostApiReferralData, ThrowOnError>) {
        return (options?.client ?? client).post<PostApiReferralResponses, unknown, ThrowOnError>({
            url: '/api/Referral',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getApiReferralByReferralCode<ThrowOnError extends boolean = false>(options: Options<GetApiReferralByReferralCodeData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiReferralByReferralCodeResponses, unknown, ThrowOnError>({ url: '/api/Referral/{referralCode}', ...options });
    }
}
