// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5130' | (string & {});
};

export type CreateReferralRequest = {
    name?: string | null;
    phoneNumber?: string | null;
};

export type CreateReferralResponse = {
    success?: boolean;
    message?: string | null;
    referralCode?: string | null;
};

export type MarkRedeemedRequest = {
    referralCode?: string | null;
};

export type MarkRedeemedResponse = {
    success?: boolean;
    message?: string | null;
};

export type ReferralDetailsResponse = {
    referrerName?: string | null;
    phoneNumber?: string | null;
    referralCode?: string | null;
    isRedeemed?: boolean;
    createdAt?: string;
    redeemedAt?: string | null;
};

export type PostApiAdminRedeemData = {
    body?: MarkRedeemedRequest;
    path?: never;
    query?: never;
    url: '/api/Admin/redeem';
};

export type PostApiAdminRedeemResponses = {
    /**
     * OK
     */
    200: MarkRedeemedResponse;
};

export type PostApiAdminRedeemResponse = PostApiAdminRedeemResponses[keyof PostApiAdminRedeemResponses];

export type PostApiReferralData = {
    body?: CreateReferralRequest;
    path?: never;
    query?: never;
    url: '/api/Referral';
};

export type PostApiReferralResponses = {
    /**
     * OK
     */
    200: CreateReferralResponse;
};

export type PostApiReferralResponse = PostApiReferralResponses[keyof PostApiReferralResponses];

export type GetApiReferralByReferralCodeData = {
    body?: never;
    path: {
        referralCode: string;
    };
    query?: never;
    url: '/api/Referral/{referralCode}';
};

export type GetApiReferralByReferralCodeResponses = {
    /**
     * OK
     */
    200: ReferralDetailsResponse;
};

export type GetApiReferralByReferralCodeResponse = GetApiReferralByReferralCodeResponses[keyof GetApiReferralByReferralCodeResponses];
