// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { Admin, type Options, Referral } from '../sdk.gen';
import type { GetApiReferralByReferralCodeData, GetApiReferralByReferralCodeResponse, PostApiAdminRedeemData, PostApiAdminRedeemResponse, PostApiReferralData, PostApiReferralResponse } from '../types.gen';

export const postApiAdminRedeemMutation = (options?: Partial<Options<PostApiAdminRedeemData>>): UseMutationOptions<PostApiAdminRedeemResponse, DefaultError, Options<PostApiAdminRedeemData>> => {
    const mutationOptions: UseMutationOptions<PostApiAdminRedeemResponse, DefaultError, Options<PostApiAdminRedeemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Admin.postApiAdminRedeem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiReferralMutation = (options?: Partial<Options<PostApiReferralData>>): UseMutationOptions<PostApiReferralResponse, DefaultError, Options<PostApiReferralData>> => {
    const mutationOptions: UseMutationOptions<PostApiReferralResponse, DefaultError, Options<PostApiReferralData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Referral.postApiReferral({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiReferralByReferralCodeQueryKey = (options: Options<GetApiReferralByReferralCodeData>) => createQueryKey('getApiReferralByReferralCode', options);

export const getApiReferralByReferralCodeOptions = (options: Options<GetApiReferralByReferralCodeData>) => queryOptions<GetApiReferralByReferralCodeResponse, DefaultError, GetApiReferralByReferralCodeResponse, ReturnType<typeof getApiReferralByReferralCodeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Referral.getApiReferralByReferralCode({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiReferralByReferralCodeQueryKey(options)
});
